// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiD5ZsYHqhuaOUWQ7rn82ZdP7Ww5pKr0k',
    appId: '1:697786801169:web:4ca849026412de9195e5b0',
    messagingSenderId: '697786801169',
    projectId: 'skala-mobile',
    authDomain: 'skala-mobile.firebaseapp.com',
    storageBucket: 'skala-mobile.appspot.com',
    measurementId: 'G-Q3QGEYHZLP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqeN5shrF2Y8efWLz-8mtGXode_pzN4fU',
    appId: '1:697786801169:android:b35efc0dafa5061b95e5b0',
    messagingSenderId: '697786801169',
    projectId: 'skala-mobile',
    storageBucket: 'skala-mobile.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAis_fzUn6yjROFqpf7UqTe86QYqH3jURU',
    appId: '1:697786801169:ios:f6c8438cb6814eee95e5b0',
    messagingSenderId: '697786801169',
    projectId: 'skala-mobile',
    storageBucket: 'skala-mobile.appspot.com',
    iosClientId: '697786801169-fnno6cbfpakqhme4a0rq2jgsarmtoadp.apps.googleusercontent.com',
    iosBundleId: 'com.example.skalaMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAis_fzUn6yjROFqpf7UqTe86QYqH3jURU',
    appId: '1:697786801169:ios:f6c8438cb6814eee95e5b0',
    messagingSenderId: '697786801169',
    projectId: 'skala-mobile',
    storageBucket: 'skala-mobile.appspot.com',
    iosClientId: '697786801169-fnno6cbfpakqhme4a0rq2jgsarmtoadp.apps.googleusercontent.com',
    iosBundleId: 'com.example.skalaMobile',
  );
}
